services:
  postgres:
    image: postgres:16
    container_name: purr_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: purr
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./deploy/initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d purr"]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 30s
    restart: unless-stopped

  metabase:
    image: metabase/metabase:latest
    container_name: purr_metabase
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_HOST: postgres
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres

      # чтобы на 1GB не умирал
      MB_JAVA_OPTS: "-Xms128m -Xmx512m"
    ports:
      - "3000:3000"
    restart: unless-stopped

  etl_runner:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: purr
      DB_USER: postgres
      DB_PASSWORD: postgres
      TZ: Europe/Moscow
      ETL_LOOKBACK_DAYS: "30"
      TEST_CUSTOMER_ID: "47533921"
    command: python -m src.cli.update_all
    restart: "no"

volumes:
  postgres_data: